# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-01 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='configPort',
            field=models.IntegerField(verbose_name='Configuration port'),
        ),
        migrations.AlterField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='site',
            name='hostname',
            field=models.CharField(max_length=20, verbose_name='Hostname'),
        ),
        migrations.AlterField(
            model_name='site',
            name='mqPort',
            field=models.IntegerField(blank=True, verbose_name='Message queue port'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
    ]
