# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0002_auto_20160801_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='supervisordPort',
            field=models.IntegerField(default=9001, verbose_name='Supervisord port'),
        ),
        migrations.AlterField(
            model_name='site',
            name='configPort',
            field=models.IntegerField(default=8888, verbose_name='Configuration port'),
        ),
        migrations.AlterField(
            model_name='site',
            name='mqPort',
            field=models.IntegerField(blank=True, default=5672, verbose_name='Message queue port'),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
