# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-08 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurator', '0003_auto_20160808_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='configPort',
            field=models.CharField(default='8888', max_length=5, verbose_name='Configuration port'),
        ),
        migrations.AlterField(
            model_name='site',
            name='mqPort',
            field=models.CharField(blank=True, default='5672', max_length=5, verbose_name='Message queue port'),
        ),
        migrations.AlterField(
            model_name='site',
            name='supervisordPort',
            field=models.CharField(default='9001', max_length=5, verbose_name='Supervisord port'),
        ),
    ]
