#!/bin/sh

daemon_name=EventNotifierService

. /etc/rc.conf
. /etc/rc.d/functions

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/mono/mono-service
NAME=EventNotifierService
DESC=EventNotifierService

MONOSERVER=$(which mono-service)
MONOSERVER_PID=$(cat /tmp/EventNotifierService.lock)

case "$1" in
 start)
  stat_busy "Starting ${NAME}"
  if [ -z "${MONOSERVER_PID}" ]; then
   ${MONOSERVER} -l:/tmp/EventNotifierService.lock ~/projects/git/doorbell/EventNotifier/EventNotifierService/bin/Debug/EventNotifierService.exe
   stat_done
  else
   echo "${NAME} is already running!"
   stat_fail
  fi
 ;;
 stop)
  stat_busy "Stopping ${NAME}"
  if [ -n "${MONOSERVER_PID}" ]; then
   kill ${MONOSERVER_PID}
   rm /tmp/EventNotifierService.lock
   stat_done
  else
   echo "${NAME} is not running"
   stat_fail
  fi
 ;;
 restart)
  $0 stop
  sleep 1
  $0 start
  stat_done
 ;;
 *)
  echo "usage: $0 {start|stop|restart}"
esac

exit 0
