- hosts: testserver
  tasks:
  - name: Copy FruitHAP Engine to ~/fruithap/engine
    synchronize: src=engine dest=/home/pi/fruithap/ delete=yes recursive=yes
  - name: Copy Pushbullet notifier to ~/fruithap/pushbullet-notifier 
    synchronize: src=pushbullet-notifier dest=/home/pi/fruithap/ delete=yes recursive=yes
  - name: Copy init scripts to temp dir
    synchronize: src=initscripts dest=/home/pi/ delete=yes recursive=yes
  - name: Add user pi to group dialout
    user: name=pi groups=dialout append=yes
  - name: Install required npm packages for pushbullet-notifier
    npm: path=/home/pi/fruithap/pushbullet-notifier
# Todo: startup scripts and starting service

