- hosts: testserver
  tasks:
  - name: Copy FruitHAP Engine to ~/fruithap/engine
    synchronize: src=engine dest=/home/pi/fruithap/ delete=yes recursive=yes 
        rsync_opts:
          - "--exclude=.json"
          - "--exclude=.config"
  - name: Copy Pushbullet notifier to ~/fruithap/pushbullet-notifier 
    synchronize: src=pushbullet-notifier dest=/home/pi/fruithap/ recursive=yes
  - name: Copy supervisor config
    copy: src=initscripts/supervisord.conf dest=/etc/
  - name: Copy supervisor init script
    copy: src=initscripts/supervisord.sh /etc/init.d/supervisor
  - name: Create log directory for supervisord
    file: path=/var/log/supervisord/ state=directory

  - name: Add user pi to group dialout
    user: name=pi groups=dialout append=yes
  - name: Install required npm packages for pushbullet-notifier
    npm: path=/home/pi/fruithap/pushbullet-notifier
  - name: Start service supervisor and configure it to run on startup
    service: name=supervisor enabled=yes started=started

